### PR TITLE
added the feature to save the output

### PR DESCRIPTION
**Pull request by adith-p**
the output will be saved in the current directory as a text file  named as "textfile.txt"  
the saved data will be  replaced  when the new info is generated

### CODE REVIEW

**Review by harshakshit — COMMENTED** [review]
I think you don't need f.close(line 47) if you're using " with open " (line 34)

Make it work more efficiently, then I can merge it

**Comment by adith-p** [comment]
ok thank you i will o it asap

**Comment by adith-p** [comment]
I will do it asap

**Comment by adith-p** [comment]
so I was thinking why don't we use append instead of write in "with open"

**Pull request merged**
